### ISSUE TITLE
Unclonable

### ISSUE THREAD

**Issue by Zleub** [airstruck/hell#1]
Hi !

I wannna give a try at your repo but it's missing a dependency. If you wish, you should replace your symlink by a git-submodule, it's kind of build for that purpose.

**Comment by airstruck** [comment]
It's a relative symlink, you should be able to clone [airstruck/knife](https://github.com/airstruck/knife) next to airstruck/hell and it will work.

The problem is it links to a directory inside of the other repo, and I'm not sure there's a clean way to set that up as a submodule. Maybe we can do it as a subtree. That would be nice, since people wouldn't have to do the extra submodule stuff when cloning.

**Comment by airstruck** [comment]
I think the subtree solution is a good one. The entire knife source tree is in the repo now, but cloning should "just work" and I can pull in changes easily with `git pull -s subtree ../knife`

**Comment by airstruck** [comment]
Subtrees are also a pain, git makes a bad guess when using subtree merge strategy and puts the subtree in the sprites directory (and deletes all sprites) instead of putting it where it's supposed to go. May have to use submodules after all. Will think about this more.

**Comment by airstruck** [comment]
For now I've done the simplest possible thing and just copied the library into this project.

**Comment by Zleub** [comment]
Thanks for let me try this !

My guess is that subtrees are different than submodule's. [Reference](https://git-scm.com/book/en/v1/Git-Tools-Submodules). It allow you to `point (?)` to a particular commit of a particular repository without having to merge content with you're actual repo. It's quite handy concerning static dependencies over libraries and such without being sensitive about modifications and only requires a bunch of command to initialize. After, everything work like a regular folder.

**Comment by airstruck** [comment]
Yeah, the problem with submodules is people need to do extra work to clone the repo. After you clone the repo, you need to do something like `git submodule init; git submodule update`, and I'd have to document that. I'd also have to do extra steps if I want to update that library... It's too much trouble for a simple thing like this (and there are [other](https://codingkilledthecat.wordpress.com/2012/04/28/why-your-company-shouldnt-use-git-submodules/) [reasons](http://somethingsinistral.net/blog/git-submodules-are-probably-not-the-answer/) to stay away from submodules).

**Comment by Zleub** [comment]
I do understand more of your reluctance now.
